### 混淆矩阵

![jupyter](./混淆矩阵.png)

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [4]:
digist = datasets.load_digits()

In [6]:
x = digist.data
y = digist.target.copy()

In [7]:
y[digist.target == 9] = 1
y[digist.target != 9] = 0

In [9]:
y[:30]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1])

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
train_x, test_x, train_y, test_y = train_test_split(x,y, random_state = 666)

In [12]:
from sklearn.linear_model import LogisticRegression

In [18]:
logistic_reg = LogisticRegression()

In [19]:
logistic_reg.fit(train_x, train_y)
logistic_reg.score(test_x, test_y)

e:\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.9755555555555555

In [20]:
predict_y = logistic_reg.predict(test_x)

In [21]:
def TN(test_y, predict_y):
    return np.sum((test_y==0)&(predict_y==0))

In [22]:
def FP(test_y, predict_y):
    return np.sum((test_y==0)&(predict_y==1))

In [23]:
def FN(test_y, predict_y):
    return np.sum((test_y==1)&(predict_y==0))

In [24]:
def TP(test_y, predict_y):
    return np.sum((test_y==1)&(predict_y==1))

In [38]:
def confusion_matrix(test_y, predict_y):
    return np.array([
        [TN(test_y, predict_y), FP(test_y, predict_y)],
        [FN(test_y, predict_y), TP(test_y, predict_y)]
    ])

In [26]:
TN(test_y, predict_y)

403

In [27]:
FN(test_y, predict_y)

9

In [28]:
FP(test_y, predict_y)

2

In [29]:
TP(test_y, predict_y)

36

In [39]:
confusion_matrix(test_y, predict_y)

array([[403,   2],
       [  9,  36]])

### 精准率， 召回率

### 精准率
![jupyter](./精准率.png)

### 召回率
![jupyter](./召回率.png)

In [47]:
def precision_score(test_y, predict_y):
    try:
        return TP(test_y, predict_y)/(TP(test_y, predict_y) + FP(test_y, predict_y))
    except:
        return 0.0

In [48]:
def recall_score(test_y, predict_y):
    try:
        return TP(test_y, predict_y)/(TP(test_y, predict_y) + FN(test_y, predict_y))
    except:
        return 0.0

In [49]:
precision_score(test_y, predict_y)

0.9473684210526315

In [50]:
recall_score(test_y, predict_y)

0.8

### sklearn中的混淆矩阵， 精准率， 召回率 

In [51]:
from sklearn.metrics import confusion_matrix

In [52]:
confusion_matrix(test_y, predict_y)

array([[403,   2],
       [  9,  36]], dtype=int64)

In [53]:
from sklearn.metrics import precision_score, recall_score

In [54]:
precision_score(test_y, predict_y)

0.9473684210526315

In [55]:
recall_score(test_y, predict_y)

0.8