### 什么是轮廓
#### 轮廓可以简单认为成将连续的点（连着边界）连在一起的曲线，具有相同、的颜色或者灰度。轮廓在形状分析和物体的检测和识别中很有用。
####   • 为了更加准确，要使用二值化图像。在寻找轮廓之前，要进行阈值化处理、或者 Canny 边界检测。
####   • 查找轮廓的函数会修改原始图像。如果你在找到轮廓之后还想使用原始图、像的话，你应该将原始图像存储到其他变量中。
####   • 在 OpenCV 中，查找轮廓就像在黑色背景中超白色物体。你应该记住，、要找的物体应该是白色而背景应该是黑色。
#### 让我们看看如何在一个二值图像中查找轮廓：
####   函数 cv2.findContours() 有三个参数，第一个是输入图像，第二个是轮廓检索模式，第三个是轮廓近似方法。返回值有三个，第一个是图像，第二个是轮廓，第三个是（轮廓的）层析结构。
####   轮廓（第二个返回值）是一个 Python列表，其中存储这图像中的所有轮廓。每一个轮廓都是一个 Numpy 数组，包含对象边界点（x，y）的坐标。
####   注意：我们后边会对第二和第三个参数，以及层次结构进行详细介绍。在那之前，例子中使用的参数值对所有图像都是适用的。

### 绘制轮廓
#### 函数 cv2.drawContours() 可以被用来绘制轮廓。它可以根据你提供的边界点绘制任何形状。它的第一个参数是原始图像，第二个参数是轮廓，一个 Python 列表。
#### 第三个参数是轮廓的索引（在绘制独立轮廓是很有用，当设置为 -1 时绘制所有轮廓）。接下来的参数是轮廓的颜色和厚度等

In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

In [2]:
img = cv2.imread('f:/opencv/img/cat2.jpg')
img_cp = img.copy()
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
ret, thresh = cv2.threshold(img_gray, 127, 255, cv2.THRESH_BINARY_INV)
## cv2.CHAIN_APPROX_NONE 记录轮廓所有点 cv2.CHAIN_APPROX_SIMPLE 记录轮廓近似点（如：直线只记录两个端点） 
contours, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE) 
img_contour = cv2.drawContours(img, contours, -1, (0,255,0), 3)  ## 第三个参数为contours 的索引， -1 表示画全部轮廓
cv2.imshow('img', img_cp)
cv2.imshow('img_gray', img_gray)
cv2.imshow('thresh', thresh)
cv2.imshow('img_contour', img_contour)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
### 画一个简单的图测试

In [4]:
img = np.zeros((300, 600, 3), dtype = np.uint8)
img = cv2.rectangle(img, (50, 50), (250, 250), (255,255,255), -1)
points = np.array([[350, 150], [420, 120], [450, 50], [480, 120],[550, 150], [480, 180], [450, 250], [420, 180]], dtype = np.int32)
points = points.reshape((-1,1,2)) 
print(points)
#img = cv2.polylines(img,[points],True,(255,255,255), 1)
img = cv2.fillPoly(img,[points],(255,255,255))
img_cp = img.copy()
cv2.imwrite('f:/opencv/img/rect_star.jpg', img)

cv2.imshow('img', img_cp)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[350 150]]

 [[420 120]]

 [[450  50]]

 [[480 120]]

 [[550 150]]

 [[480 180]]

 [[450 250]]

 [[420 180]]]


In [5]:
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
ret, thresh = cv2.threshold(img_gray, 127, 255, cv2.THRESH_BINARY)
contours, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE) 
img_contour = cv2.drawContours(img, contours, 0, (0,255,0), 3)  ## 第三个参数为contours 的索引， -1 表示画全部轮廓  note: drawContours会改变原img的值
cv2.imshow('img', img_cp)
cv2.imshow('img_contour', img_contour)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
### 轮廓特征
#### 轮廓的不同特征，例如面积，周长，重心，边界框， 函数 cv2.moments() 会将计算得到的矩阵以一个字典的形式返回各特征值

In [7]:
img = cv2.imread('f:/opencv/img/rect_star.jpg')
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
ret, thresh = cv2.threshold(img_gray, 127, 255, cv2.THRESH_BINARY)
contours, hierarchy = cv2.findContours(thresh, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
img_contour = cv2.drawContours(img, contours, 1, (0,255,0), 2)  ## 第三个参数为contours 的索引， -1 表示画全部轮廓  
contour = contours[1]
M = cv2.moments(contour)
print(M)
cv2.imshow('img', img_gray)
cv2.imshow('contour', img_contour)
cv2.waitKey(0)
cv2.destroyAllWindows()

{'m00': 40000.0, 'm10': 6000000.0, 'm01': 6000000.0, 'm20': 1033333333.3333333, 'm11': 900000000.0, 'm02': 1033333333.3333333, 'm30': 195000000000.0, 'm21': 155000000000.0, 'm12': 155000000000.0, 'm03': 195000000000.0, 'mu20': 133333333.33333325, 'mu11': 0.0, 'mu02': 133333333.33333325, 'mu30': 3.0517578125e-05, 'mu21': 1.1444091796875e-05, 'mu12': 1.1444091796875e-05, 'mu03': 3.0517578125e-05, 'nu20': 0.08333333333333329, 'nu11': 0.0, 'nu02': 0.08333333333333329, 'nu30': 9.5367431640625e-17, 'nu21': 3.5762786865234375e-17, 'nu12': 3.5762786865234375e-17, 'nu03': 9.5367431640625e-17}


In [8]:
### 轮廓的重心(cx, cy): 

cx = M['m10']/M['m00']
cy = M['m01']/M['m00']
print('cx: {}  cy: {}'.format(cx, cy))

cx: 150.0  cy: 150.0


In [9]:
### 轮廓面积
area = cv2.contourArea(contour)
print('area: {}'.format(area))  ##200*200

area: 40000.0


In [10]:
### 轮廓周长
perimeter = cv2.arcLength(contour, True) ## 第二个参数表示对像是封闭的还是打开的（曲线）
print('perimeter:', perimeter)

perimeter: 800.0


In [11]:
### 轮廓近似
contour = contours[0]
epsilon = 0.1 * cv2.arcLength(contour, True)       
approx = cv2.approxPolyDP(contour, epsilon, True)
approx = approx.reshape((-1, 1, 2))
img_cp = img_gray.copy()
img_contour = cv2.polylines(img_cp, [approx], True, (0,255,0), 3) 
cv2.imshow('contour', img_contour)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 凸包
#### 凸包与轮廓近似相似，但不同，虽然有些情况下它们给出的结果是一样的。函数 cv2.convexHull() 可以用来检测一个曲线是否具有凸性缺陷，并能纠正缺陷。
#### 一般来说，凸性曲线总是凸出来的，至少是平的。如果有地方凹进去了就被叫做凸性缺陷。例如下图中的手。红色曲线显示了手的凸包，凸性缺陷被双箭头标出来了。
![jupyter](./tubao.png)
#### 用法 hull = cv2.convexHull(points[, hull[, clockwise[, returnPoints]]
#### 参数：
#### 　　• points 我们要传入的轮廓
#### 　　• hull 输出，通常不需要
#### 　　• clockwise 方向标志。如果设置为 True，输出的凸包是顺时针方向的。否则为逆时针方向。
#### 　　• returnPoints 默认值为 True。它会返回凸包上点的坐标。如果设置为 False，就会返回与凸包点对应的轮廓上的点。
#### 要获得上图的凸包，下面的命令就够了：
#### hull = cv2.convexHull(cnt)

### 凸性检测
#### 函数 cv2.isContourConvex() 可以可以用来检测一个曲线是不是凸的。它只能返回 True 或 False
#### k = cv2.isContourConvex(cnt)

### 边界矩形
#### 直边界矩形： 一个直矩形（就是没有旋转的矩形）。它不会考虑对象是否旋转。所以边界矩形的面积不是最小的。可以使用函数 cv2.boundingRect() 查找得到。
#### （x，y）为矩形左上角的坐标，（w，h）是矩形的宽和高。
#### x,y,w,h = cv2.boundingRect(cnt)
#### img = cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),2)
#### 旋转的边界矩形： 这个边界矩形是面积最小的，因为它考虑了对象的旋转。用到的函数为 cv2.minAreaRect()。返回的是一个 Box2D 结构，其中包含矩形左上角角点的坐标（x，y），矩形的宽和高（w，h），以及旋转角度。
#### 但是要绘制这个矩形需要矩形的 4 个角点，可以通过函数 cv2.boxPoints() 获得。
#### rect = cv2.minAreaRect(cnt)
#### box = cv2.boxPoints(rect)
#### box = np.int0(box)
#### im = cv2.drawContours(im,[box],0,(0,0,255),2)

In [ ]:
### 未完待续