In [1]:
## color palette

In [2]:
import cv2
import numpy as np

In [3]:
def doNothing(x):
    pass

In [4]:
img = np.full((1000, 1000, 3), 255, np.uint8)
cv2.namedWindow('img-show', cv2.WINDOW_NORMAL)
cv2.createTrackbar('R', 'img-show', 0, 255, doNothing)
cv2.createTrackbar('G', 'img-show', 0, 255, doNothing)
cv2.createTrackbar('B', 'img-show', 0, 255, doNothing)

while(True):
    if cv2.waitKey(8) == ord('q'):
        break
    
    r = cv2.getTrackbarPos('R', 'img-show')
    g = cv2.getTrackbarPos('G', 'img-show')
    b = cv2.getTrackbarPos('B', 'img-show')
    
    img[:] = [b,g,r]
    cv2.imshow('img-show', img)
cv2.destroyAllWindows()


In [5]:
### img add
### 像素相加

In [6]:
a = 250
b = 20 
print(a+b)

270


In [7]:
a = np.uint8([250])
b = np.uint8([20])
print(cv2.add(a,b))
print(a+b)

[[255]]
[14]


### 图片相加 权重
![jupyter](./pic_weight.jpg)

In [8]:
img1 = cv2.imread('F:/opencv/img/opencv1.jpg')
img2 = cv2.imread('F:/opencv/img/opencv2.jpg')
img1 = cv2.resize(img1, (150, 185))
dst_img = cv2.addWeighted(img1, 0.7, img2, 0.3, 0)
cv2.imshow('dst-img', dst_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
## 图片按位运算

In [30]:
img1 = cv2.imread('F:/opencv/img/cat1.jpg')
img1_cp = img1.copy()
img2 = cv2.imread('F:/opencv/img/opencv2.jpg')
cv2.namedWindow('img1', cv2.WINDOW_AUTOSIZE)
cv2.imshow('img1', img1)
cv2.namedWindow('img2', cv2.WINDOW_AUTOSIZE)
cv2.imshow('img2', img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [31]:
rows, cols, channels = img2.shape
roi = img1[0:rows, 0:cols]

In [32]:
img2gray = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)
ret, mask = cv2.threshold(img2gray, 10, 255, cv2.THRESH_BINARY)
mask_inv = cv2.bitwise_not(mask)

In [33]:
img1_bg = cv2.bitwise_and(roi, roi, mask = mask_inv)
img2_bg = cv2.bitwise_and(img2, img2, mask= mask)

In [34]:
dst = cv2.add(img1_bg, img2_bg)
img1[0:rows, 0:cols] = dst

In [35]:
cv2.imshow('img1', img1_cp)
cv2.imshow('img2', img2)
cv2.imshow('res', img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [16]:
print(mask)

[[255 255 255 ... 255 255 255]
 [255   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [255   0   0 ...   0   0   0]
 [255   0   0 ...   0   0   0]
 [255   0   0 ...   0   0   0]]


In [17]:
print(mask_inv)

[[  0   0   0 ...   0   0   0]
 [  0 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [  0 255 255 ... 255 255 255]
 [  0 255 255 ... 255 255 255]
 [  0 255 255 ... 255 255 255]]


In [36]:
### 像素按位运算与掩码

In [45]:
base = np.zeros((300, 300), dtype = np.uint8)
rect = cv2.rectangle(base, (25, 25), (275,275), 255, -1)
base = np.zeros((300, 300), dtype = np.uint8)
circle = cv2.circle(base, (150, 150), 150, 255, -1)
base = np.zeros((300, 300), dtype = np.uint8)
mask = cv2.rectangle(base, (15, 15), (130, 100), 255, -1)
mask_inv = cv2.bitwise_not(mask)

bitwise_and = cv2.bitwise_and(rect, circle)
bitwise_or = cv2.bitwise_or(rect, circle)
bitwise_xor = cv2.bitwise_xor(rect, circle)

bitwise_and_mask = cv2.bitwise_and(rect, circle, mask = mask)
bitwise_and_maskinv = cv2.bitwise_and(rect, circle, mask = mask_inv)
bitwise_or_mask = cv2.bitwise_or(rect, circle, mask = mask)

cv2.imshow('rect', rect)
cv2.imshow('circle', circle)
cv2.imshow('mask', mask)
cv2.imshow('mask_inv', mask_inv)
cv2.imshow('and', bitwise_and)
cv2.imshow('or', bitwise_or)
cv2.imshow('xor', bitwise_xor)
cv2.imshow('and_mask', bitwise_and_mask)
cv2.imshow('and_maskinv', bitwise_and_maskinv)
cv2.imshow('or_mask', bitwise_or_mask)

cv2.waitKey(0)
cv2.destroyAllWindows()