In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
raw_data_X = [[3.393533211, 2.331273381],
              [3.110073483, 1.781539638],
              [1.343808831, 3.368360954],
              [3.582294042, 4.679179110],
              [2.280362439, 2.866990263],
              [7.423436942, 4.696522875],
              [5.745051997, 3.533989803],
              [9.172168622, 2.511101045],
              [7.792783481, 3.424088941],
              [7.939820817, 0.791637231]
             ]

In [5]:
raw_data_y = [0,0,0,0,0,1,1,1,1,1]

In [6]:
x_train = np.array(raw_data_X)
y_train = np.array(raw_data_y)

In [7]:
x = np.array([8.093607318, 3.365731514])

In [8]:
%run KNN_func/kNN.py

In [10]:
predict_y = kNN_classify(6, x_train, y_train, x)

In [11]:
predict_y

1

In [12]:
x1 = np.array([1,1])
predict_y1 = kNN_classify(6, x_train, y_train, x1)
predict_y1

0

## 使用sklearn 的knn分类算法

In [13]:
from sklearn.neighbors import KNeighborsClassifier

In [15]:
kNN_classifier = KNeighborsClassifier(n_neighbors = 6)

In [17]:
kNN_classifier.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=6, p=2,
                     weights='uniform')

In [25]:
predict_y =  kNN_classifier.predict(x.reshape(1,-1))

In [27]:
predict_y

array([1])

In [22]:
predict_y1 = kNN_classifier.predict(x1.reshape(1,-1))

In [28]:
predict_y1

array([0])

## 调用手动封装的knn分类器

In [38]:
%run kNN/kNN.py

In [39]:
knn_clf = KNNClassifier(k=6)

In [40]:
knn_clf.fit(x_train, y_train)

KNN(k=6)

In [41]:
knn_clf.predict(x.reshape(1,-1))

array([1])

In [42]:
knn_clf.predict(x1.reshape(1,-1))

array([0])