## numpy.array 基础

In [1]:
import numpy

In [2]:
numpy.__version__

'1.18.1'

In [3]:
import numpy as np

In [4]:
np.__version__

'1.18.1'

In [5]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
L[5] = 100

In [7]:
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [8]:
L[4] = "test"
L

[0, 1, 2, 3, 'test', 100, 6, 7, 8, 9]

In [9]:
import array

In [10]:
arr = array.array('i', [i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr[5] = 100

In [12]:
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

## numpy 向量与矩阵操作

In [13]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
nparr[5] = 100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [16]:
nparr.dtype

dtype('int32')

In [17]:
nparr[4] = 4.0
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [18]:
nparr[3]= 3.3333
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [19]:
nparr2 = np.array([1,2,3.333])
nparr.dtype

dtype('int32')

In [20]:
nparr2.dtype

dtype('float64')

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [24]:
np.zeros(shape=(3,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [25]:
np.ones(shape=(2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.full(shape=(2,4), fill_value=66)

array([[66, 66, 66, 66],
       [66, 66, 66, 66]])

In [27]:
np.full(shape=(2,4), 666)

SyntaxError: positional argument follows keyword argument (<ipython-input-27-9d8ee612a075>, line 1)

In [28]:
np.full(shape=(2,4), fill_value= 666, dtype=float)

array([[666., 666., 666., 666.],
       [666., 666., 666., 666.]])

## numpy  arange 


In [29]:
[i for i in range(0, 20, 2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [30]:
np.arange(0, 10, )

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.arange(0, 1, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

## linspace


In [32]:
np.linspace(0, 20, 10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [33]:
np.linspace(0, 22, 10)

array([ 0.        ,  2.44444444,  4.88888889,  7.33333333,  9.77777778,
       12.22222222, 14.66666667, 17.11111111, 19.55555556, 22.        ])

In [34]:
np.linspace(0, 20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [35]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

## numpy random

In [36]:
np.random.randint(0, 10)

7

In [37]:
np.random.randint(0,10, 10)

array([6, 5, 0, 1, 0, 3, 0, 8, 8, 0])

In [38]:
np.random.randint(0,1, 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [39]:
np.random.randint(0,5, size=10)

array([1, 2, 4, 3, 4, 0, 0, 4, 2, 0])

In [40]:
np.random.randint(0,5, size=(3,4))

array([[4, 2, 0, 2],
       [0, 3, 4, 1],
       [4, 3, 2, 0]])

In [41]:
np.random.seed(12)
np.random.randint(2, 7, size=(3,4))

array([[5, 5, 3, 4],
       [5, 5, 6, 2],
       [3, 6, 3, 4]])

In [44]:
np.random.seed(12)
np.random.randint(2, 7, size=(3,4))


array([[5, 5, 3, 4],
       [5, 5, 6, 2],
       [3, 6, 3, 4]])

In [45]:
np.random.random(10)

array([0.72595416, 0.37283446, 0.67599758, 0.98364716, 0.48153021,
       0.91253883, 0.18987634, 0.14797388, 0.90726736, 0.68432507])

In [46]:
np.random.random((3,4))

array([[0.95772873, 0.45605092, 0.56314114, 0.80126538],
       [0.94317762, 0.22335928, 0.70293978, 0.49994509],
       [0.20266072, 0.62936457, 0.14429873, 0.05295153]])

In [47]:
np.random.normal()

0.11888055327618119

In [48]:
np.random.normal(10, 100)

-0.8949261486436733

In [49]:
np.random.normal(10, 100)

22.43139448903385

In [50]:
np.random.normal(10, 100)

-93.46721753703689

In [51]:
np.random.normal(0, 1, size=(3,4))

array([[ 1.86194108, -1.34626923, -0.91379068, -1.08023723],
       [ 0.24473064,  0.13554853, -1.14786946,  0.23358559],
       [ 0.77621522, -0.57704715,  2.02427573, -1.67302387]])

In [53]:
np.random.normal?

In [54]:
np.random?