In [1]:
import numpy as np

In [2]:
L = np.random.random(size = 100)
L

array([0.47760956, 0.7735065 , 0.12626346, 0.91041738, 0.97885918,
       0.01208868, 0.25222597, 0.74498542, 0.66985778, 0.69948123,
       0.25223855, 0.23135319, 0.95216904, 0.37742855, 0.37358943,
       0.9585347 , 0.90552323, 0.99821958, 0.52601009, 0.59394831,
       0.96059777, 0.6727546 , 0.45357141, 0.33683384, 0.15292795,
       0.21544736, 0.72693867, 0.76703874, 0.43674066, 0.7179503 ,
       0.82235293, 0.96044214, 0.21593518, 0.16990113, 0.14634675,
       0.07662631, 0.44493767, 0.64348268, 0.69830486, 0.1029721 ,
       0.10047914, 0.65645683, 0.29918764, 0.26210251, 0.1920536 ,
       0.58437687, 0.16914296, 0.1695131 , 0.02882776, 0.10308566,
       0.36869483, 0.48307726, 0.19780481, 0.92975398, 0.70826899,
       0.47453754, 0.26800143, 0.7805381 , 0.29356107, 0.25070249,
       0.62982975, 0.16770968, 0.75013921, 0.17514426, 0.92048099,
       0.79017826, 0.54085462, 0.90225622, 0.67256647, 0.97869023,
       0.8153168 , 0.14055524, 0.10013749, 0.84557822, 0.29315

In [3]:
sum(L)

50.35519811819755

In [4]:
np.sum(L)

50.355198118197535

In [5]:
bigL = np.random.random(1000000)
%timeit sum(bigL)
%timeit np.sum(bigL)

283 ms ± 19.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
1.6 ms ± 157 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
np.min(L)

0.01208868181264644

In [7]:
np.max(L)

0.9982195796394439

In [8]:
L.min()

0.01208868181264644

In [9]:
L.max()

0.9982195796394439

In [10]:
X = np.arange(1,17).reshape(4, -1)

In [11]:
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [12]:
np.sum(X)

136

In [13]:
np.sum(X, axis = 0)

array([28, 32, 36, 40])

In [14]:
np.sum(X, axis = 1)

array([10, 26, 42, 58])

In [15]:
Y = np.arange(16).reshape(-1, 8)
Y

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [16]:
np.prod(X) # X的所有元素相乘

2004189184

In [17]:
np.mean(X)

8.5

In [18]:
np.median(X)  # 中位数

8.5

In [19]:
v = np.array([1,1,2,2,10])

In [20]:
np.mean(v)

3.2

In [21]:
np.median(v) 

2.0

In [22]:
np.percentile(v, 50) # 50 指50% 中位数。  这个函数有统计学中有重要意义。 比如前20%，30%的数等等。

2.0

In [23]:
bigL[0:10]

array([0.91711827, 0.18122977, 0.61432733, 0.76339403, 0.80701073,
       0.7494135 , 0.14958527, 0.68071431, 0.35157941, 0.40810983])

In [24]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(bigL, percent))

9.255136479424664e-08
0.25043451690803475
0.5004636279683015
0.7497815589952758
0.9999980197574317


In [25]:
np.var(bigL)

0.08319258234193799

In [26]:
np.std(bigL)

0.28843124369932255

In [27]:
np.sqrt(np.var(bigL)) 

0.28843124369932255

In [28]:
x = np.random.normal(0,1, size = 10000)

In [29]:
np.mean(x)

-0.007244071642112301

In [30]:
np.std(x)

1.0047599246625147

### 索引

In [31]:
np.min(x)

-3.944256209550629

In [32]:
np.argmin(x)

5263

In [33]:
x[7664]

0.7679593046708953

In [34]:
np.argmax(x)

3811

In [35]:
x[np.argmax(x)]

3.8164583563594157

In [36]:
np.max(x)

3.8164583563594157

## 排序 使用索引

In [37]:
x = np.arange(16)

In [38]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [39]:
np.random.shuffle(x)

In [40]:
x

array([12,  6,  0,  4,  2, 13,  9, 14,  3, 11, 10, 15,  1,  7,  5,  8])

In [41]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [42]:
x

array([12,  6,  0,  4,  2, 13,  9, 14,  3, 11, 10, 15,  1,  7,  5,  8])

In [43]:
x.sort()

In [44]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [45]:
X = np.random.randint(16, size=(4, 4))
X

array([[ 9, 15, 14,  8],
       [ 2,  4, 11, 11],
       [ 8,  6, 15, 13],
       [ 5,  0,  9,  6]])

In [46]:
np.sort(X)

array([[ 8,  9, 14, 15],
       [ 2,  4, 11, 11],
       [ 6,  8, 13, 15],
       [ 0,  5,  6,  9]])

In [47]:
np.sort(X, axis = 0)

array([[ 2,  0,  9,  6],
       [ 5,  4, 11,  8],
       [ 8,  6, 14, 11],
       [ 9, 15, 15, 13]])

In [48]:
np.sort(X, axis = 1)

array([[ 8,  9, 14, 15],
       [ 2,  4, 11, 11],
       [ 6,  8, 13, 15],
       [ 0,  5,  6,  9]])

In [49]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [50]:
np.random.shuffle(x)

In [51]:
x

array([ 5,  7, 13, 12,  4,  9,  3,  8,  1,  6,  0, 11, 15,  2, 14, 10])

In [52]:
np.argsort(x)

array([10,  8, 13,  6,  4,  0,  9,  1,  7,  5, 15, 11,  3,  2, 14, 12],
      dtype=int64)

In [53]:
x

array([ 5,  7, 13, 12,  4,  9,  3,  8,  1,  6,  0, 11, 15,  2, 14, 10])

In [54]:
np.partition(x, 4) # 以4为边界分区， 小于4的在左边， 大于4的在右边

array([ 0,  1,  3,  2,  4,  6,  5,  7,  8,  9, 12, 11, 15, 13, 14, 10])

In [55]:
np.argpartition(x, 4)

array([10,  8,  6, 13,  4,  9,  0,  1,  7,  5,  3, 11, 12,  2, 14, 15],
      dtype=int64)

In [56]:
X

array([[ 9, 15, 14,  8],
       [ 2,  4, 11, 11],
       [ 8,  6, 15, 13],
       [ 5,  0,  9,  6]])

In [57]:
np.argsort(X, axis = 1)

array([[3, 0, 2, 1],
       [0, 1, 2, 3],
       [1, 0, 3, 2],
       [1, 0, 3, 2]], dtype=int64)

In [58]:
X

array([[ 9, 15, 14,  8],
       [ 2,  4, 11, 11],
       [ 8,  6, 15, 13],
       [ 5,  0,  9,  6]])

In [59]:
X.partition(3)

In [60]:
X

array([[ 8,  9, 14, 15],
       [ 2,  4, 11, 11],
       [ 6,  8, 13, 15],
       [ 0,  5,  6,  9]])

## fancy indexing

In [61]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [62]:
x[3:6]

array([3, 4, 5])

In [63]:
x[3:9:3]

array([3, 6])

In [64]:
x[3:9:2]

array([3, 5, 7])

In [65]:
[x[2],x[3],x[5]]

[2, 3, 5]

In [66]:
index = [2,3,5]
x[index]

array([2, 3, 5])

In [67]:
index1 = np.array([[2, 3],
                 [6, 7]])
x[index1]

array([[2, 3],
       [6, 7]])

In [68]:
X = x.reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [69]:
row = np.array([0,1,2])
col = np.array([0,2,3])
X[row, col]

array([ 0,  6, 11])

In [70]:
X[1, col]

array([4, 6, 7])

In [71]:
X[2:3, col]

array([[ 8, 10, 11]])

In [72]:
X[row, 1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [73]:
col = [True, False, True, True]
X[:3, col]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11]])

## numpy 比较

In [74]:
x = np.arange(10)

In [75]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [77]:
x >= 8

array([False, False, False, False, False, False, False, False,  True,
        True])

In [78]:
X = np.arange(16).reshape(4,-1)

In [79]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [80]:
X > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [81]:
X[X>3]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [82]:
X < 3

array([[ True,  True,  True, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [83]:
np.sum(x < 3)

3

In [84]:
np.any(x == 3)

True

In [85]:
np.any(x == 11)

False

In [86]:
np.all(x > 0)

False

In [87]:
np.all(x >=0)

True

In [88]:
np.sum(X%2 == 0)

8

In [89]:
np.sum(X%2 == 0, axis = 1)

array([2, 2, 2, 2])

In [90]:
np.sum(X%2 == 0, axis = 0)

array([4, 0, 4, 0])

In [91]:
(x>3)&(x<=6)

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [92]:
np.sum((X <3) |(X>10))

8

In [93]:
np.sum(~(x==0))

9

In [94]:
x[x < 4]

array([0, 1, 2, 3])

In [95]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [96]:
X[X[:, 3] % 3 == 0, :]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])