## numpy.array 中的运算
 a = (1,2,3)
 a*2 = (2,4,6)

In [1]:
n = 10
L = [i for i in range(n)]

In [2]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
L*2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
A = []
for i in L:
    A.append(2*i)
A

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [5]:
%%timeit
A = []
for i in L:
    A.append(2*i)
A

1.72 µs ± 278 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [6]:
%%timeit
A=[2*i for i in range(n)]


1.55 µs ± 126 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [7]:
%%timeit
import numpy as np

L = np.array(2*i for i in range(n))

3.59 µs ± 271 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [8]:
L = [1,2,3]
L1 = L*2
L1

[1, 2, 3, 1, 2, 3]

In [9]:
import numpy as np

In [10]:
L = np.array([1,2,3])
L1 = L*2 
L1

array([2, 4, 6])

## universal functions 

In [11]:
X = np.arange(1, 16).reshape((3,5))
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [12]:
X + 1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [13]:
X - 2

array([[-1,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13]])

In [14]:
 X * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [15]:
X / 2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [16]:
X // 2

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]], dtype=int32)

In [17]:
X % 2

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]], dtype=int32)

In [18]:
1/X 

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [19]:
np.abs(X)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [20]:
np.sin(X)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [21]:
np.cos(X)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153],
       [ 0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791]])

In [22]:
np.exp(X)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [23]:
np.power(3, X)

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]], dtype=int32)

In [24]:
3 ** X

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]], dtype=int32)

In [25]:
np.log(X)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [26]:
np.log2(X)

array([[0.        , 1.        , 1.5849625 , 2.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809],
       [3.45943162, 3.5849625 , 3.70043972, 3.80735492, 3.9068906 ]])

In [27]:
np.log10(X)

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ],
       [0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ],
       [1.04139269, 1.07918125, 1.11394335, 1.14612804, 1.17609126]])

## 矩阵间的运算

In [28]:
A = np.arange(4).reshape((2,2))

In [29]:
A

array([[0, 1],
       [2, 3]])

In [30]:
B = np.full((2,2), fill_value = 10)

In [31]:
B

array([[10, 10],
       [10, 10]])

In [32]:
A + B

array([[10, 11],
       [12, 13]])

In [33]:
A - B 

array([[-10,  -9],
       [ -8,  -7]])

In [34]:
A * B

array([[ 0, 10],
       [20, 30]])

In [35]:
A / B

array([[0. , 0.1],
       [0.2, 0.3]])

## 上述的矩阵间乘法/除法 并不是传统意义上的矩阵乘除。。 而是按行/列 数字依次做乘法，除法 传统意义上矩阵只有乘法， 没有除法 传统意义上矩阵乘法 a.dot(b)

In [36]:
A.dot(B)

array([[10, 10],
       [50, 50]])

In [37]:
A

array([[0, 1],
       [2, 3]])

In [38]:
A.T

array([[0, 2],
       [1, 3]])

In [39]:
A = np.arange(1,7).reshape((2,3))

In [40]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
B = np.arange(1,7).reshape((3,2))

In [42]:
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
A.dot(B)

array([[22, 28],
       [49, 64]])

## 向量与矩阵的运算 

In [44]:
v = np.array([1,2])

In [45]:
A = np.arange(1,5).reshape((2,2))

In [46]:
A

array([[1, 2],
       [3, 4]])

In [47]:
v  + A

array([[2, 4],
       [4, 6]])

In [48]:
np.vstack([v] * A.shape[0])

array([[1, 2],
       [1, 2]])

In [57]:
np.vstack((v, A[1])) 

array([[1, 2],
       [3, 4]])