## 使用sklearn 数据归一化后采用knn分类

In [1]:
import numpy as np
from sklearn import datasets


In [2]:
iris = datasets.load_iris()

In [3]:
iris.data[:10, :]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [4]:
x = iris.data
y = iris.target


In [5]:
from sklearn.model_selection import train_test_split

train_x, test_x, train_y, test_y = train_test_split(x, y, test_size = 0.2, random_state = 666)

In [6]:
train_x.shape

(120, 4)

In [7]:
test_x.shape

(30, 4)

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
standard_scaler = StandardScaler()

In [10]:
standard_scaler.fit(train_x)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [11]:
standard_scaler.mean_

array([5.83416667, 3.08666667, 3.70833333, 1.17      ])

In [12]:
standard_scaler.scale_

array([0.81019502, 0.44327067, 1.76401924, 0.75317107])

In [13]:
s_train_x = standard_scaler.transform(train_x)
s_train_x[:10, :]

array([[-0.90616043,  0.93246262, -1.30856471, -1.28788802],
       [-1.15301457, -0.19551636, -1.30856471, -1.28788802],
       [-0.16559799, -0.64670795,  0.22203084,  0.17260355],
       [ 0.45153738,  0.70686683,  0.95898425,  1.50032315],
       [-0.90616043, -1.32349533, -0.40154513, -0.09294037],
       [ 1.43895396,  0.25567524,  0.56216318,  0.30537551],
       [ 0.3281103 , -1.09789954,  1.0723617 ,  0.30537551],
       [ 2.1795164 , -0.19551636,  1.63924894,  1.23477923],
       [-0.78273335,  2.2860374 , -1.25187599, -1.42065998],
       [ 0.45153738, -2.00028272,  0.44878573,  0.43814747]])

In [14]:
np.mean(s_train_x[:, 0])

1.3026616822268502e-15

In [15]:
np.std(s_train_x[:, 0])

1.0000000000000002

In [16]:
from sklearn.neighbors import KNeighborsClassifier
knn_clf = KNeighborsClassifier(n_neighbors=3)

In [17]:
knn_clf.fit(s_train_x, train_y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [18]:
s_test_x = standard_scaler.transform(test_x)

In [19]:
s_test_x[:10, :]

array([[-0.28902506, -0.19551636,  0.44878573,  0.43814747],
       [-0.04217092, -0.64670795,  0.78891808,  1.63309511],
       [-1.0295875 , -1.77468693, -0.23147896, -0.22571233],
       [-0.04217092, -0.87230374,  0.78891808,  0.96923531],
       [-1.52329579,  0.03007944, -1.25187599, -1.28788802],
       [-0.41245214, -1.32349533,  0.16534211,  0.17260355],
       [-0.16559799, -0.64670795,  0.44878573,  0.17260355],
       [ 0.82181859, -0.19551636,  0.8456068 ,  1.10200727],
       [ 0.57496445, -1.77468693,  0.39209701,  0.17260355],
       [-0.41245214, -1.09789954,  0.39209701,  0.03983159]])

In [20]:
knn_clf.score(s_test_x, test_y)

1.0

In [21]:
knn_clf.score(test_x, test_y)

0.3333333333333333

In [22]:
test_x[:10]

array([[5.6, 3. , 4.5, 1.5],
       [5.8, 2.8, 5.1, 2.4],
       [5. , 2.3, 3.3, 1. ],
       [5.8, 2.7, 5.1, 1.9],
       [4.6, 3.1, 1.5, 0.2],
       [5.5, 2.5, 4. , 1.3],
       [5.7, 2.8, 4.5, 1.3],
       [6.5, 3. , 5.2, 2. ],
       [6.3, 2.3, 4.4, 1.3],
       [5.5, 2.6, 4.4, 1.2]])

In [23]:
mean = [np.mean(test_x[:, i]) for i in range(0, test_x.shape[1])]

In [24]:
mean

[5.88, 2.94, 3.9566666666666666, 1.3166666666666667]

In [25]:
scale = [np.std(test_x[:, i]) for i in range(0, test_x.shape[1])]

In [26]:
scale

[0.8821942340928481,
 0.3746998799039039,
 1.7265926625067716,
 0.7742020982204123]