In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [3]:
iris = datasets.load_iris()
x = iris.data
y = iris.target

In [4]:
x.shape

(150, 4)

In [5]:
y.shape

(150,)

## train test split
1. shuffle
2. split 

In [7]:
shuffle_index = np.random.permutation(len(x)) # 小于len(x)的随机序列 
shuffle_index

array([ 49, 132,  58,  97,  80,  94, 104,  48,  55,  50,  13,  65,  19,
         1, 145,   3, 134,  75,   4,  56, 101, 117, 148,  88, 146,  79,
        37,  31,  68,  17,  76, 129,  29, 147, 116,  33,  87, 121,  93,
       114,  74, 120, 127, 103, 133,  39, 100,  71,  53,  18,  10,  78,
       102, 135,  89,  16,  32,  83, 110, 130, 142,   6,  44,  73,  69,
        62, 140, 136,   0,  98,  22,  38, 107,  84,  67,  70, 124,  43,
        81,  25,  20,   9, 122,  36,  95, 105, 112,  11,  57, 137,  42,
        91,  15, 115,   8,  61,  14,  46,  34,  72,  86,  63,  28,  60,
       118,  35, 125,  52,  27,  82,  90,  66, 131,  47,  45,   7,  96,
       111, 143, 149,  54,  85,  12,  41, 109,  64, 144, 119,  30,  21,
        23, 113,  51, 106,  92,  24, 128, 138,  40, 141,  99,   2,  26,
        59, 108, 139,  77,   5, 126, 123])

In [8]:
test_redio = 0.2
test_size = int(len(x) * test_redio)

In [9]:
test_size

30

In [12]:
test_index = shuffle_index[:test_size]
train_index = shuffle_index[test_size:]

In [13]:
test_index.shape

(30,)

In [14]:
train_index.shape

(120,)

In [15]:
x_train = x[train_index]
y_train = y[train_index]

x_test = x[test_index]
y_test = y[test_index]

In [19]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [26]:
newy = y.reshape(-1, 1)
newy

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [28]:
union_data = np.concatenate((x,newy), axis = 1)
union_data

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [4.6, 3.4, 1.4, 0.3, 0. ],
       [5. , 3.4, 1.5, 0.2, 0. ],
       [4.4, 2.9, 1.4, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [5.4, 3.7, 1.5, 0.2, 0. ],
       [4.8, 3.4, 1.6, 0.2, 0. ],
       [4.8, 3. , 1.4, 0.1, 0. ],
       [4.3, 3. , 1.1, 0.1, 0. ],
       [5.8, 4. , 1.2, 0.2, 0. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [5.4, 3.9, 1.3, 0.4, 0. ],
       [5.1, 3.5, 1.4, 0.3, 0. ],
       [5.7, 3.8, 1.7, 0.3, 0. ],
       [5.1, 3.8, 1.5, 0.3, 0. ],
       [5.4, 3.4, 1.7, 0.2, 0. ],
       [5.1, 3.7, 1.5, 0.4, 0. ],
       [4.6, 3.6, 1. , 0.2, 0. ],
       [5.1, 3.3, 1.7, 0.5, 0. ],
       [4.8, 3.4, 1.9, 0.2, 0. ],
       [5. , 3. , 1.6, 0.2, 0. ],
       [5. , 3.4, 1.6, 0.4, 0. ],
       [5.2, 3.5, 1.5, 0.2, 0. ],
       [5.2, 3.4, 1.4, 0.2, 0. ],
       [4.7, 3

In [32]:
np.random.shuffle(union_data)  
union_data

array([[5.4, 3. , 4.5, 1.5, 1. ],
       [7.1, 3. , 5.9, 2.1, 2. ],
       [6.8, 3. , 5.5, 2.1, 2. ],
       [5.2, 4.1, 1.5, 0.1, 0. ],
       [7. , 3.2, 4.7, 1.4, 1. ],
       [5.1, 2.5, 3. , 1.1, 1. ],
       [6.4, 2.7, 5.3, 1.9, 2. ],
       [6.2, 2.9, 4.3, 1.3, 1. ],
       [5.9, 3.2, 4.8, 1.8, 1. ],
       [6.4, 3.2, 5.3, 2.3, 2. ],
       [4.8, 3.4, 1.6, 0.2, 0. ],
       [4.9, 3.6, 1.4, 0.1, 0. ],
       [5.7, 2.9, 4.2, 1.3, 1. ],
       [6.2, 2.2, 4.5, 1.5, 1. ],
       [5.8, 2.7, 3.9, 1.2, 1. ],
       [5.9, 3. , 4.2, 1.5, 1. ],
       [5. , 2.3, 3.3, 1. , 1. ],
       [4.4, 3.2, 1.3, 0.2, 0. ],
       [7.2, 3. , 5.8, 1.6, 2. ],
       [6.4, 3.2, 4.5, 1.5, 1. ],
       [6.1, 2.6, 5.6, 1.4, 2. ],
       [5.4, 3.9, 1.3, 0.4, 0. ],
       [5.7, 3. , 4.2, 1.2, 1. ],
       [6.4, 2.9, 4.3, 1.3, 1. ],
       [5.5, 2.3, 4. , 1.3, 1. ],
       [5.3, 3.7, 1.5, 0.2, 0. ],
       [4.4, 2.9, 1.4, 0.2, 0. ],
       [6.7, 3.1, 4.7, 1.5, 1. ],
       [5.5, 2.4, 3.8, 1.1, 1. ],
       [7.7, 3

In [33]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [39]:
union_data = np.hstack((x,y.reshape(-1,1)))

In [40]:
union_data

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [4.6, 3.4, 1.4, 0.3, 0. ],
       [5. , 3.4, 1.5, 0.2, 0. ],
       [4.4, 2.9, 1.4, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [5.4, 3.7, 1.5, 0.2, 0. ],
       [4.8, 3.4, 1.6, 0.2, 0. ],
       [4.8, 3. , 1.4, 0.1, 0. ],
       [4.3, 3. , 1.1, 0.1, 0. ],
       [5.8, 4. , 1.2, 0.2, 0. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [5.4, 3.9, 1.3, 0.4, 0. ],
       [5.1, 3.5, 1.4, 0.3, 0. ],
       [5.7, 3.8, 1.7, 0.3, 0. ],
       [5.1, 3.8, 1.5, 0.3, 0. ],
       [5.4, 3.4, 1.7, 0.2, 0. ],
       [5.1, 3.7, 1.5, 0.4, 0. ],
       [4.6, 3.6, 1. , 0.2, 0. ],
       [5.1, 3.3, 1.7, 0.5, 0. ],
       [4.8, 3.4, 1.9, 0.2, 0. ],
       [5. , 3. , 1.6, 0.2, 0. ],
       [5. , 3.4, 1.6, 0.4, 0. ],
       [5.2, 3.5, 1.5, 0.2, 0. ],
       [5.2, 3.4, 1.4, 0.2, 0. ],
       [4.7, 3